[package]
name = "tldr-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }