lint:
  aspects:
    - "@aspect_rules_lint//lint:eslint.bzl%eslint"
    - "@aspect_rules_lint//lint:ruff.bzl%ruff"

configure:
  languages:
    javascript: true
    go: true
    python: true
    protobuf: true
    bzl: true
    rust: true