[package]
name = "gt7-telemetry-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { workspace = true }
byteorder = { workspace = true }
salsa20 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
kafka = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
futures-util = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }

[dev-dependencies]
http-body-util = { workspace = true }
tower = { workspace = true }
tokio-tungstenite = { workspace = true }
