[package]
name = "gt7-telemetry-server"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.9.1", features = ["serde"] }
byteorder = "1.5.0"
salsa20 = "0.10.2"
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pulsar = "6.3.1"
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8.4", features = ["ws"] }
axum-extra = { version = "0.10.0", features = ["typed-header"] }
futures-util = "0.3"
openssl = { version = "0.10.59", features = ["vendored"] }

[dev-dependencies]
http-body-util = "0.1.3"
tower = "0.5.2"
tokio-tungstenite = "0.27"
futures-util = "0.3"
