[package]
name = "gt7-pulsar-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.9.1", features = ["serde"] }
byteorder = "1.5.0"
salsa20 = "0.10.2"
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pulsar = "6.3.1"
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
axum = "0.8.4"

[dev-dependencies]
http-body-util = "0.1.3"
tower = "0.5.2"
