version: '3.8'

services:
  gt7-pulsar-bridge:
    build:
      context: .
    ports:
      - "8080:8080"
      - "33740:33740/udp"
    environment:
      # For Docker Desktop, host.docker.internal usually resolves to the host's IP.
      # Otherwise, replace with your actual host IP if PS5 is on the same network,
      # or the PS5's IP address if it's accessible.
      PS5_IP_ADDRESS: "host.docker.internal"
      PULSAR_SERVICE_URL: "pulsar://pulsar:6650"
      PULSAR_TOPIC: "persistent://public/default/gt7-telemetry"
      RUST_LOG: "info,gt7_pulsar_bridge=debug" # Adjust log levels as needed
      HTTP_BIND_ADDRESS: "0.0.0.0:8080"
    depends_on:
      pulsar:
        condition: service_healthy
    networks:
      - gt7_testing_net

  pulsar:
    image: apachepulsar/pulsar:3.3.0
    hostname: pulsar
    command: >
      sh -c "bin/apply-config-from-env.py conf/standalone.conf &&
             bin/pulsar standalone"
    ports:
      - "6650:6650"
      - "8081:8080"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m "
      PULSAR_CLUSTER_NAME: "standalone"
      PULSAR_PREFIX_advertisedAddress: "pulsar"
      PULSAR_PREFIX_bindAddress: "0.0.0.0"
      PULSAR_PREFIX_brokerServicePort: "6650"
      PULSAR_PREFIX_webServicePort: "8080"
      PULSAR_PREFIX_bookkeeper_bookie_bardziej_Xmx: "256m"
      PULSAR_PREFIX_bookkeeper_bookie_bardziej_Xms: "256m"
      PULSAR_PREFIX_bookkeeper_ml_bardziej_Xmx: "256m"
      PULSAR_PREFIX_bookkeeper_ml_bardziej_Xms: "256m"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8080/admin/v2/brokers/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 75s # Pulsar standalone can take a significant time to initialize fully
    networks:
      - gt7_testing_net

networks:
  gt7_testing_net:
    driver: bridge
