name: Build airflow image with dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "airflow/**"

jobs:
  airflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          minor-identifier: feat
          major-identifier: feat!
          log-path: airflow/
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |-
            VENDOR=${{ github.repository_owner }}
            VERSION=${{ steps.version.outputs.version }}
            REVISION=${{ github.sha }}
          file: ./airflow/Dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/solanyn/build_cache:airflow-amd64,mode=max
          cache-to: type=registry,ref=ghcr.io/solanyn/build_cache:airflow-amd64
          push: true
          outputs: type=image,name=ghcr.io/solanyn/airflow,push-by-digest=true,name-canonical=true,push=true

