name: Build airflow image with dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "airflow/"

jobs:
  airflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Semver run
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        with:
          repository_url: https://github.com/solanyn/goyangi
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./airflow/Dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/solanyn/airflow:${{ steps.semver.outputs.semantic_version }}
