name: Build Airflow Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "airflow/**"

jobs:
  airflow:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.1
        with:
          release-branch: main
          minor-identifier: feat
          major-identifier: feat!
          log-paths: airflow/
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            var-cache-apt
            var-lib-apt
          key: cache-${{ hashFiles('airflow/Dockerfile') }}

      - name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.2.0
        with:
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ./airflow/Dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/solanyn/airflow:${{ steps.version.outputs.version }},ghcr.io/solanyn/airflow:latest
          push: true
