name: Build airflow image with dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "airflow/**"
    
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  airflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          minor-identifier: feat
          major-identifier: feat!
          log-paths: airflow/
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./airflow/Dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/solanyn/build_cache:airflow-amd64,mode=max
          cache-to: type=registry,ref=ghcr.io/solanyn/build_cache:airflow-amd64
          outputs: type=image,name=ghcr.io/solanyn/airflow,push-by-digest=true,name-canonical=true,push=true
          tags: ghcr.io/solanyn/airflow:${{ steps.version.outputs.version }}, ghcr.io/solanyn/airflow:latest
          push: true
      
