name: Build airflow image with dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "airflow/**"

jobs:
  airflow:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main
          minor-identifier: feat
          major-identifier: feat!
          log-paths: airflow/
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ./airflow/Dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/solanyn/build_cache:airflow-amd64,mode=max
          cache-to: type=registry,ref=ghcr.io/solanyn/build_cache:airflow-amd64
          tags: ghcr.io/solanyn/airflow:${{ steps.version.outputs.version }},ghcr.io/solanyn/airflow:latest
          push: true
